package de.qaware.openapigeneratorforspring.common.reference.component.requestbody;

import de.qaware.openapigeneratorforspring.common.reference.fortype.ReferenceIdentifierConflictResolverForType;
import de.qaware.openapigeneratorforspring.model.requestbody.RequestBody;

public interface ReferenceIdentifierConflictResolverForRequestBody extends ReferenceIdentifierConflictResolverForType<RequestBody> {

}
